simplify posix.yml

diff --git a/.github/workflows/posix.yml b/.github/workflows/posix.yml
--- a/.github/workflows/posix.yml
+++ b/.github/workflows/posix.yml
@@ -24,25 +24,25 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          - { os: ubuntu-latest, PLAT: i686, INTERFACE64: '0', MB_ML_VER: '2014', MB_ML_LIBC: manylinux}
+          # - { os: ubuntu-latest, PLAT: i686, INTERFACE64: '0', MB_ML_VER: '2014', MB_ML_LIBC: manylinux}
 
-          - { os: ubuntu-latest, PLAT: x86_64, INTERFACE64: '0', MB_ML_VER: '2014', MB_ML_LIBC: manylinux}
+          # - { os: ubuntu-latest, PLAT: x86_64, INTERFACE64: '0', MB_ML_VER: '2014', MB_ML_LIBC: manylinux}
           - { os: ubuntu-latest, PLAT: x86_64, INTERFACE64: '1', MB_ML_VER: '2014', MB_ML_LIBC: manylinux}
 
-          - { os: macos-latest, PLAT: x86_64, INTERFACE64: '0', MB_ML_VER: '2014', MB_ML_LIBC: manylinux}
-          - { os: macos-latest, PLAT: x86_64, INTERFACE64: '1', MB_ML_VER: '2014', MB_ML_LIBC: manylinux}
+          # - { os: macos-latest, PLAT: x86_64, INTERFACE64: '0', MB_ML_VER: '2014', MB_ML_LIBC: manylinux}
+          # - { os: macos-latest, PLAT: x86_64, INTERFACE64: '1', MB_ML_VER: '2014', MB_ML_LIBC: manylinux}
 
-          - { os: macos-latest, PLAT: arm64, INTERFACE64: '0'}
-          - { os: macos-latest, PLAT: arm64, INTERFACE64: '1'}
+          # - { os: macos-latest, PLAT: arm64, INTERFACE64: '0'}
+          # - { os: macos-latest, PLAT: arm64, INTERFACE64: '1'}
 
-          - { os: ubuntu-latest, PLAT: x86_64, INTERFACE64: '0', MB_ML_VER: '_1_2', MB_ML_LIBC: musllinux}
-          - { os: ubuntu-latest, PLAT: x86_64, INTERFACE64: '1', MB_ML_VER: '_1_2', MB_ML_LIBC: musllinux}
+          # - { os: ubuntu-latest, PLAT: x86_64, INTERFACE64: '0', MB_ML_VER: '_1_2', MB_ML_LIBC: musllinux}
+          # - { os: ubuntu-latest, PLAT: x86_64, INTERFACE64: '1', MB_ML_VER: '_1_2', MB_ML_LIBC: musllinux}
 
-          - { os: ubuntu-24.04-arm, PLAT: aarch64, INTERFACE64: '0', MB_ML_VER: '2014'}
-          - { os: ubuntu-24.04-arm, PLAT: aarch64, INTERFACE64: '1', MB_ML_VER: '2014'}
+          # - { os: ubuntu-24.04-arm, PLAT: aarch64, INTERFACE64: '0', MB_ML_VER: '2014'}
+          # - { os: ubuntu-24.04-arm, PLAT: aarch64, INTERFACE64: '1', MB_ML_VER: '2014'}
 
-          - { os: ubuntu-24.04-arm, PLAT: aarch64, INTERFACE64: '0', MB_ML_VER: '_1_2', MB_ML_LIBC: musllinux}
-          - { os: ubuntu-24.04-arm, PLAT: aarch64, INTERFACE64: '1', MB_ML_VER: '_1_2', MB_ML_LIBC: musllinux}
+          # - { os: ubuntu-24.04-arm, PLAT: aarch64, INTERFACE64: '0', MB_ML_VER: '_1_2', MB_ML_LIBC: musllinux}
+          # - { os: ubuntu-24.04-arm, PLAT: aarch64, INTERFACE64: '1', MB_ML_VER: '_1_2', MB_ML_LIBC: musllinux}
 
     env:
       NIGHTLY: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
@@ -53,12 +53,13 @@ jobs:
       INTERFACE64: ${{ matrix.INTERFACE64 }}
       BUILD_DIR: ${{ github.workspace }}
       PLAT: ${{ matrix.PLAT }}
+      OS-NAME: ${{ matrix.os }}
 
     steps:
     - uses: actions/checkout@v4.1.1
       with:
         submodules: recursive
-        fetch-depth: 0
+        fetch-depth: 1
     - name: Set up Python
       uses: actions/setup-python@v5
       with:
@@ -66,6 +67,23 @@ jobs:
     - name: Set extra env
       run: |
         echo "DOCKER_TEST_IMAGE=$(echo multibuild/xenial_${{ matrix.PLAT}})" >> $GITHUB_ENV;
+
+    # - name: Build wheels
+    #   uses: pypa/cibuildwheel@v3.1.4
+    #   with:
+    #     output-dir: dist
+    #   env:
+    #     WRAPT_INSTALL_EXTENSIONS: true
+    #     CIBW_BUILD_VERBOSITY: 1
+    #     CIBW_ARCHS: ${{ matrix.arch }}
+    #     CIBW_ENABLE: cpython-freethreading
+    #     CIBW_PROJECT_REQUIRES_PYTHON: ">=3.9"
+    # - name: Build wheels
+    #   run: python -m cibuildwheel --output-dir wheelhouse
+      # to supply options, put them in 'env', like:
+      # env:
+      #   CIBW_SOME_OPTION: value
+      #   ...
 
     - uses: maxim-lobanov/setup-xcode@v1.6.0
       if: ${{ matrix.os == 'macos-latest' }}
@@ -76,58 +94,64 @@ jobs:
       run: |
         echo "PLAT: ${PLAT}"
         echo "DOCKER_TEST_IMAGE: ${DOCKER_TEST_IMAGE}"
-    - name: Install VirtualEnv
-      run: |
-        python3 -m pip install --upgrade pip
-        pip install virtualenv
     - name: Build OpenBLAS
-      run: |
-        set -xeo pipefail
-        source tools/build_steps.sh
-        echo "------ BEFORE BUILD ---------"
-        before_build
-        if [[ "$NIGHTLY" = "true" ]]; then
-          echo "------ CLEAN CODE --------"
-          clean_code $REPO_DIR develop
-          echo "------ BUILD LIB --------"
-          build_lib "$PLAT" "$INTERFACE64" "1"
-        else
-          echo "------ CLEAN CODE --------"
-          clean_code $REPO_DIR $OPENBLAS_COMMIT
-          echo "------ BUILD LIB --------"
-          build_lib "$PLAT" "$INTERFACE64" "0"
-        fi
+      run: ./build-openblas.sh
 
-    # - name: Setup tmate session
-    #   if: ${{ failure() }}
-    #   uses: mxschmitt/action-tmate@v3
-    #   with:
-    #     limit-access-to-actor: true
+    # - name: Install VirtualEnv
+    #   run: |
+    #     python3 -m pip install --upgrade pip
+    #     pip install virtualenv
+    # - name: Build OpenBLAS
+    #   run: |
+    #     set -xeo pipefail
+    #     source tools/build_steps.sh
+    #     echo "------ BEFORE BUILD ---------"
+    #     before_build
+    #     if [[ "$NIGHTLY" = "true" ]]; then
+    #       echo "------ CLEAN CODE --------"
+    #       clean_code $REPO_DIR develop
+    #       echo "------ BUILD LIB --------"
+    #       build_lib "$PLAT" "$INTERFACE64" "1"
+    #     else
+    #       echo "------ CLEAN CODE --------"
+    #       clean_code $REPO_DIR $OPENBLAS_COMMIT
+    #       echo "------ BUILD LIB --------"
+    #       build_lib "$PLAT" "$INTERFACE64" "0"
+    #     fi
 
+    # # - name: Setup tmate session
+    # #   if: ${{ failure() }}
+    # #   uses: mxschmitt/action-tmate@v3
+    # #   with:
+    # #     limit-access-to-actor: true
     - name: Build and test wheel
       run: |
-        if [[ "$NIGHTLY" = "true" ]]; then
-          # Set the pyproject.toml version: convert v0.3.24-30-g138ed79f to 0.3.34.30
-          version=$(cd OpenBLAS && git describe --tags --abbrev=8 | sed -e "s/^v\(.*\)-g.*/\1/" | sed -e "s/-/./g")
-          sed -e "s/^version = .*/version = \"${version}\"/" -i.bak pyproject.toml
-        fi
-        if [ "macos-latest" == "${{ matrix.os }}" ]; then
-          source tools/build_wheel.sh
-        else
-          libc=${MB_ML_LIBC:-manylinux}
-          docker_image=quay.io/pypa/${libc}${MB_ML_VER}_${PLAT}
-          docker run --rm -e INTERFACE64="${INTERFACE64}" \
-            -e MB_ML_LIBC="${MB_ML_LIBC}" \
-            -v $(pwd):/openblas $docker_image \
-            /bin/bash -xe /openblas/tools/build_wheel.sh
-          sudo chmod -R a+w dist
-        fi
+        ./build-wheel.sh
+    # - name: Build and test wheel
+    #   run: |
+    #     if [[ "$NIGHTLY" = "true" ]]; then
+    #       # Set the pyproject.toml version: convert v0.3.24-30-g138ed79f to 0.3.34.30
+    #       version=$(cd OpenBLAS && git describe --tags --abbrev=8 | sed -e "s/^v\(.*\)-g.*/\1/" | sed -e "s/-/./g")
+    #       sed -e "s/^version = .*/version = \"${version}\"/" -i.bak pyproject.toml
+    #     fi
+    #     if [ "macos-latest" == "${ OS-NAME }" ]; then
+    #       source tools/build_wheel.sh
+    #     else
+    #       libc=${MB_ML_LIBC:-manylinux}
+    #       docker_image=quay.io/pypa/${libc}${MB_ML_VER}_${PLAT}
+    #       docker run --rm -e INTERFACE64="${INTERFACE64}" \
+    #         -e MB_ML_LIBC="${MB_ML_LIBC}" \
+    #         -v $(pwd):/openblas $docker_image \
+    #         /bin/bash -xe /openblas/tools/build_wheel.sh
+    #       sudo chmod -R a+w dist
+    #     fi
 
     - uses: actions/upload-artifact@v4.3.0
       with:
         name: wheels-${{ matrix.os }}-${{ matrix.PLAT }}-${{ matrix.INTERFACE64 }}-${{ matrix.MB_ML_LIBC }}-${{ matrix.MB_ML_VER }}
         path: dist/scipy_openblas*.whl
 
+    # 把cibuildwheel的openblas编译结果从容器里面copy出来
     - uses: actions/upload-artifact@v4.3.0
       with:
         name: openblas-${{ matrix.os }}-${{ matrix.PLAT }}-${{ matrix.INTERFACE64 }}-${{ matrix.MB_ML_LIBC }}-${{ matrix.MB_ML_VER }}
